# Generated by Django 3.0.6 on 2020-05-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200512_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
